services:
  - type: web
    name: my-bot
    env: python
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    runtime: python

build:
  pythonVersion: 3.10.13
